#!/usr/bin/env bash
FILES=/usr/local/bin/ihfcode/extensions
for f in $FILES/*.vsix; do
  [ -e "$f" ] || continue
  f0=$(basename -a $f)
  f1=$(basename -s .vsix $f)
  mkdir -p $FILES/$f1
  cd $FILES && cat $FILES/$f0 | bsdtar -xvf - extension
  mv $FILES/extension /home/coder/.local/share/code-server/extensions/$f1
done

dumb-init /usr/local/bin/ihfcode/code-server /home/coder/project --auth none
